name: CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: victron-venus/venus-os-ci-toolkit/.github/workflows/python-ci.yml@3f7d3ff94d1c693f32f4f92d17f7eb04883b4e7e
    with:
      python-version: '3.12.13'
      use-uv-lock: true
      build-dependency-group: build
