name: CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: victron-venus/venus-os-ci-toolkit/.github/workflows/python-ci.yml@dc1cc0b02ecdec3e121934975655ca02fceea763
    with:
      python-version: '3.12.13'
      use-uv-lock: true
      build-dependency-group: build
